{
 "title": "Containers : CPU, Memory, I/O Monitor",
 "description": "Monitors container deployments in cluster using Prometheus. Shows overall cluster CPU / Memory used, as well as split by container, kube-system etc. Uses cAdvisor metrics.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container memory usage",
   "type": "gauge",
   "description": "Total memory being used by all containers",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes)",
     "legendFormat": "Working Memory"
    },
    {
     "expr": "sum(container_memory_usage_bytes)",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Total Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "os_total_physical_memory_bytes" }
   ]
  },
  {
   "title": "Memory by Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{}) by(container_label_com_docker_compose_project, container_label_io_kubernetes_pod_namespace)",
     "legendFormat": " {{container_label_com_docker_compose_project}} | {{container_label_io_kubernetes_pod_namespace}}"
    }
   ]
  },
  {
   "title": "Total Free",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "os_free_physical_memory_bytes" }
   ]
  },
  {
   "title": "Memory by Container - Working Set (Excluding kube-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_label_io_kubernetes_pod_namespace!=\"kube-system\",name!=\"\"}) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory by Container - Working Set (kube-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_label_io_kubernetes_pod_namespace=\"kube-system\",name!=\"\"}) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory by Container - Used (Excluding kube-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_namespace!=\"kube-system\",name!=\"\"}) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory by Container - Used (kube-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_namespace=\"kube-system\",name!=\"\"}) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Container CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total[1m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum (machine_cpu_cores)" }
   ]
  },
  {
   "title": "CPU by Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_project, container_label_io_kubernetes_pod_namespace) (rate(container_cpu_usage_seconds_total[1m]))",
     "legendFormat": "{{container_label_com_docker_compose_project}} | {{container_label_io_kubernetes_pod_namespace}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[15s]))"
    }
   ]
  },
  {
   "title": "CPU by Container (Excluding kube-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace!=\"kube-system\",name!=\"\"}[15s]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU by Container (kube-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=\"kube-system\"}[15s]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Share (Excluding kube-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_spec_cpu_shares{container_label_io_kubernetes_pod_namespace!=\"kube-system\",name!=\"\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Share (kube-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_spec_cpu_shares{container_label_io_kubernetes_pod_namespace=\"kube-system\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Containers I/O and Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Containers: Running (Excluding kube-system)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(count(container_start_time_seconds{container_label_io_kubernetes_pod_namespace!=\"kube-system\",name!=\"\"}) by (name))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Containers: Running (kube-system)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "count(count(container_start_time_seconds{container_label_io_kubernetes_pod_namespace=\"kube-system\"}) by (name))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Containers: FS Write (Excluding kube-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{container_label_io_kubernetes_pod_namespace!=\"kube-system\",name!=\"\"}[15s])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers: FS Write (kube-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{container_label_io_kubernetes_pod_namespace=\"kube-system\",name!=\"\"}[15s])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers: Network Rx (Excluding kube-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_io_kubernetes_pod_namespace!=\"kube-system\",name!=\"\"}[15s])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers: Network Rx (kube-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_io_kubernetes_pod_namespace=\"kube-system\",name!=\"\"}[15s])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers: Network Tx (Excluding kube-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_io_kubernetes_pod_namespace!=\"kube-system\",name!=\"\"}[15s])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers: Network Tx (kube-system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_io_kubernetes_pod_namespace=\"kube-system\",name!=\"\"}[15s])) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}