{
 "title": "Demo Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Gatling All Requests Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       {
        "params": [
         "perfizsimulation.allRequests.all.count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "all" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "perfizsimulation.allRequests.ok.count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ok" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "perfizsimulation.allRequests.ko.count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ko" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gatling All Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       {
        "params": [
         "perfizsimulation.allRequests.all.percentiles99"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "99th percentile" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "perfizsimulation.allRequests.ok.percentiles95"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "95th percentile" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "perfizsimulation.allRequests.ok.percentiles75"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "75th percentile" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "perfizsimulation.allRequests.ok.percentiles50"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "50th percentile" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gatling Container Metrics - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_cpu_system_seconds_total{name=\"perfiz-gatling\"}",
     "legendFormat": "container_cpu_system_seconds_total"
    }
   ]
  },
  {
   "title": "Gatling Container Metrics - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{name=\"perfiz-gatling\"}",
     "legendFormat": "container_memory_max_usage_bytes"
    },
    {
     "expr": "container_memory_swap{name=\"perfiz-gatling\"}",
     "legendFormat": "container_memory_swap"
    }
   ]
  }
 ]
}